"use client";
import { useState } from "react";
import { Arrow } from "./icons";

export function ProductPreview({ variant = "booking", interactive = false, operationView = 0 }: { variant?: string; interactive?: boolean; operationView?: number }) {
  const [view, setView] = useState("Interface");
  const [day, setDay] = useState(23);
  if (variant === "editorial") return <div className="editorial-preview" aria-label="Sample brand website interface">
    <div className="editorial-top"><strong>STILL / FORM</strong><span>Objects. Spaces. Perspective.</span><Arrow diagonal /></div>
    <div className="editorial-body"><span className="micro">A STUDY IN THE EVERYDAY</span><h4>Room for<br /><em>the essential.</em></h4><div className="architectural-scene" aria-hidden="true"><div className="scene-window" /><div className="scene-plinth" /><div className="scene-vase" /><div className="scene-shadow" /></div><span className="editorial-bottom">Considered spaces, made for living.<span>COLLECTION 001 ↗</span></span></div>
  </div>;
  if (variant === "operations") return <div className="operations-preview" aria-label="Sample operations dashboard interface">
    <div className="ops-top"><span className="ops-brand">flowdesk</span><span className="ops-avatar">JD</span></div>
    <div className="ops-heading"><div><span className="micro">{["WORKSPACE / OVERVIEW", "WORKSPACE / CONNECTIONS", "WORKSPACE / DELIVERY"][operationView]}</span><h4>{["A little more clarity.", "Better, connected.", "Ready for what’s next."][operationView]}</h4></div><span className="ops-pill">This week ↓</span></div>
    <div className="ops-stats"><div><span>In progress</span><b>08</b><small>Across your workspace</small></div><div><span>Completed</span><b>24<span>↗</span></b><small>Moving things forward</small></div></div>
    <div className="ops-task"><span className="task-check" /><div><strong>{["Website handover", "Calendar → reservations", "Production checks"][operationView]}</strong><small>{["Design & development", "Sync events and availability", "Build and verify"][operationView]}</small></div><span className="task-tag">In review</span></div><div className="ops-task"><span className="task-check checked">✓</span><div><strong>{["Connect booking calendar", "Reservation → notification", "Release approved"][operationView]}</strong><small>{["Integrations", "A useful next step, automated", "Deployment workflow"][operationView]}</small></div><span className="task-tag done">Done</span></div>
    <div className="ops-chart" aria-hidden="true">{[28,42,34,60,49,75,68,87,77,100,92,112].map((height,i)=><i key={i} style={{height}} />)}</div><div className="ops-chart-label"><span>MON</span><span>WORK, IN MOTION</span><span>FRI</span></div>
  </div>;
  return <div className={`product-study ${interactive ? "interactive-study" : ""}`}>
    {interactive && <div className="study-toolbar"><span className="micro">AN INTERACTIVE STUDY</span><div className="view-switch" role="group" aria-label="Explore the interface or system">{["Interface","System"].map(v=><button key={v} onClick={()=>setView(v)} aria-pressed={view===v}>{v}</button>)}</div></div>}
    <div className="booking-window"><div className="browser-bar"><span className="browser-dots" aria-hidden="true"><i/><i/><i/></span><span>from an idea → to a working product</span><span aria-hidden="true">↗</span></div>
    {view === "System" ? <div className="system-view"><span className="micro">UNDER THE SURFACE</span><h4>One experience.<br />Connected thinking.</h4><div className="system-node"><span>01</span><strong>Customer interface</strong><small>React · Next.js</small></div><div className="system-connector">↓</div><div className="system-node"><span>02</span><strong>Application logic</strong><small>Availability · Access · Validation</small></div><div className="system-connector">↓</div><div className="system-node"><span>03</span><strong>A single source of truth</strong><small>Database · External services</small></div><p>Illustrative architecture, designed around the booking journey.</p></div> : <div className="booking-app"><aside className="booking-sidebar"><span className="stay-logo">st<span>ā</span>y.</span><span className="side-link selected"><i>▦</i>Overview</span><span className="side-link"><i>▤</i>Bookings</span><span className="side-link"><i>□</i>Properties</span><span className="side-link"><i>◷</i>Calendar</span><span className="sidebar-bottom">THOUGHTFULLY HOSTED.</span></aside><div className="booking-content"><div className="booking-heading"><div><span className="micro">YOUR DAY, AT A GLANCE</span><h4>Welcome back, Alex.</h4></div><span className="avatar">A</span></div><div className="booking-stats"><div><span>Arriving today</span><strong>{day === 23 ? "04" : "02"}</strong><small>Everything is in place <span>↗</span></small></div><div><span>Occupancy</span><strong>{day === 23 ? "86" : "72"}<em>%</em></strong><small>A good week ahead <span>↗</span></small></div></div><div className="calendar-title"><strong>September <span>2026</span></strong><span>‹ &nbsp; ›</span></div><div className="calendar-days">{[21,22,23,24,25,26,27].map((n,i)=> interactive ? <button key={n} className={day===n ? "chosen" : ""} aria-label={`Preview September ${n}`} aria-pressed={day===n} onClick={()=>setDay(n)}><span>{["M","T","W","T","F","S","S"][i]}</span><b>{n}</b></button> : <span className={n===23 ? "chosen" : ""} key={n}><span>{["M","T","W","T","F","S","S"][i]}</span><b>{n}</b></span>)}</div><div className="arrivals-label"><strong>Upcoming arrivals</strong><span>{day === 23 ? "4" : "2"} guests</span></div><div className="guest-row"><span className="guest-initial">EL</span><div><strong>{day===23 ? "Emma Lewis" : "Jamie Chen"}</strong><small>Garden suite · 2 nights</small></div><span className="confirmed">Confirmed</span></div><div className="guest-row second-guest"><span className="guest-initial peach">JT</span><div><strong>James Taylor</strong><small>Studio loft · 3 nights</small></div><span className="confirmed">Confirmed</span></div></div></div>}
    </div>
    {interactive && <div className="study-caption"><span><i /> A clear interface. A considered system.</span><small>Concept UI · illustrative data</small></div>}
  </div>;
}
